version: '3'

services:

  hf:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      PUSHGATEWAY: http://pushgateway:9091

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9092:9091

volumes:
  gem_cache:
