x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:

  hf:
    build:
      context: .
      target: base
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
      pushgateway: *healthy
    environment:
      MARIADB_HT_RO_USERNAME: ht_rights
      MARIADB_HT_RO_PASSWORD: ht_rights
      MARIADB_HT_RO_HOST: mariadb
      MARIADB_HT_RO_DATABASE: ht
      PUSHGATEWAY: http://pushgateway:9091

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9092:9091
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

volumes:
  gem_cache:
