database:
  opts:
    adapter: 'mysql2'
    host: <%= ENV['MYSQL_HOST'] %>
    database: <%= ENV['MYSQL_DATABASE'] %>
    user: <%= ENV['MYSQL_USER'] %>
    password: <%= ENV['MYSQL_PASSWORD'] %>
hathifiles_archive_path: <%= ENV["HATHIFILES_ARCHIVE_PATH"] %>
hathifiles_web_path: <%= ENV['HATHIFILES_WEB_PATH'] %>
zephir_dir: <%= ENV['ZEPHIR_DIR'] %>
hathifiles_dir: <%= ENV['HATHIFILES_DIR'] %>
